version: '3'
services:
  spring-app:
    image: dhxxn/rh_capsule:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/capsule
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: capsule157
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server /data/redis.conf
    volumes:
      - redis-data:/data
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "capsule157"
      POSTGRES_DB: "capsule"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis-data:
