spring:
  application:
    name: rh_capsule
  datasource:
    url: jdbc:postgresql://localhost:5432/rh_capsule
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamrh229@gmail.com
    password: wpnrdvlurozzeiun
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  packages-to-scan: com.rh.rh_capsule
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    disable-request-duration: true
    operations-sorter: alpha
jwt:
  secret: 788204a244246309e1638496620afceb197aef8f04e848351d9a38f33eab0d55