spring:
  application:
    name: rh_capsule
  datasource:
    url: jdbc:postgresql://15.164.199.14:5432/capsule
    username: postgres
    password: capsule157
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 15.164.199.14
      port: 6379
      password: capsule157
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamrh229@gmail.com
    password: wpnrdvlurozzeiun
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  packages-to-scan: com.rh.rh_capsule
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    disable-request-duration: true
    operations-sorter: alpha
jwt:
  secret: ab2129be4dd751c09472cf1e76a8a8ebdcd5213c20d588cd3fb400dfb7533790283b2bef0fff7afbacde0e91425b5076e83a01eca9424954591e5bdd4c89ac5e

oauth2:
  provider:
    google:
      id: 162994116258-6iph6h85fqf9hhdeg3696e0to45t69fm.apps.googleusercontent.com
      secret: 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
      info-url: https://www.googleapis.com/oauth2/v1/userinfo
      login-url: https://accounts.google.com/o/oauth2/v2/auth
      scope: email profile
      token-url: https://oauth2.googleapis.com/token
      redirect-uri: http://localhost:8080/oauth/google/signin
cloud:
  aws:
    credentials:
      access-key: AKIA3FLD2YDIBP4SAXWL
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: capsule-server-bucket
    stack:
      auto: false