name: Build and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create application.yml from Secret
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.SPRING_APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (for ARM64)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: dhxxn/rh_capsule:latest
          platforms: linux/arm64
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Raspberry Pi via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p ~/rh_capsule
            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > ~/rh_capsule/docker-compose.yml
            cd ~/rh_capsule
            docker-compose pull
            docker-compose up -d
